### ISSUE TITLE
Проверить функционал активации ваучеров пользователями

### ISSUE THREAD

**Issue by mathewsun** [mathewsun/Web-Api_online#1]
Проверить функционал активации ваучеров пользователями, авторизованных через Google
https://ecats.online/voucher/activate/GVLMEDHYHM

1 Авторизоваться через Google
2 Активировать ваучер
3 Убедиться что монеты зачислились на кошелёк
4 можно проверить перевод другому пользхователю (зарегистрировать другого пользователя)

**Comment by irina070761a** [comment]
1 .смогли авторизоваться через гугл 
2. ваучер активировали удачно 
3. монеты на кошелек зачислены

**Comment by irina070761a** [comment]
4.ЗАРЕГИСТРИВОЛИ НОВОГО ПОЛЬЗОВАТЕЛЯ в режиме инкогнито 
смогли сделать перевод от одного пользователя к другому
